[package]
name = "actix-web-ss"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
actix-web = "1"
futures = "0.1"
bytes = "0.4"
serde_json = "1.0.14"
serde = {version = "1.0.41", features = ['derive']} 